### ISSUE TITLE
ConsoleKit2 daemon segfaults randomly

### ISSUE THREAD

**Issue by awilfox** [ConsoleKit2/ConsoleKit2#115]
Sometimes it will run for a few days, sometimes it only makes it a few hours.  I can't seem to figure out anything about this crash.

Environment is musl libc 1.1.20.

```
Core was generated by `/usr/sbin/console-kit-daemon --no-daemon '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000109e83054 in emit_final_uninhibit_signals (inhibit=0x1001b859780) at ck-inhibit.c:350
350             if (CK_IS_INHIBIT (inhibit) && priv->inhibitors[CK_INHIBIT_EVENT_IDLE]) {
[Current thread is 1 (LWP 22916)]
(gdb) bt
#0  0x0000000109e83054 in emit_final_uninhibit_signals (inhibit=0x1001b859780) at ck-inhibit.c:350
#1  0x0000000109e83054 in close_named_pipe (inhibit=0x1001b859780) at ck-inhibit.c:416
#2  0x0000000109e836f4 in cb_named_pipe_close (source=<optimized out>, condition=<optimized out>, user_data=0x1001b859780) at ck-inhibit.c:442
#3  0x00003fff95d31f60 in g_io_unix_dispatch (source=0x1001b850fc0, callback=0x109e83650 <cb_named_pipe_close>, user_data=0x1001b859780) at ../glib/giounix.c:165
#4  0x00003fff95ccb0a0 in g_main_dispatch (context=0x3fff95c02060) at ../glib/gmain.c:3182
#5  0x00003fff95ccb0a0 in g_main_context_dispatch (context=0x3fff95c02060) at ../glib/gmain.c:3847
#6  0x00003fff95ccb568 in g_main_context_iterate (context=0x3fff95c02060, block=1, dispatch=1, self=<optimized out>) at ../glib/gmain.c:3920
#7  0x00003fff95ccbb70 in g_main_loop_run (loop=0x3fff95e29ea0) at ../glib/gmain.c:4116
#8  0x0000000109e67b38 in main (argc=<optimized out>, argv=<optimized out>) at main.c:307
(gdb) p priv
$1 = (CkInhibitPrivate *) 0x1001b859730
(gdb) p *priv
$2 = {who = 0x1001b85f8a0 "", inhibitors = {0, 0, -1431655766, -1431655766, -1431655766, -1431655766, -1431655766}, why = 0xaaaaaaaaaaaaaaaa <error: Cannot access memory at address 0xaaaaaaaaaaaaaaaa>, mode = 2863311530, uid = 2863311530, pid = -1431655766, 
  named_pipe = -1431655766, named_pipe_path = 0xaaaaaaaaaaaaaaaa <error: Cannot access memory at address 0xaaaaaaaaaaaaaaaa>, fd_source = -1431655766}
(gdb) p inhibit
$5 = 0x1001b859780
(gdb) p *(CkInhibit*)inhibit
$8 = {parent = {g_type_instance = {g_class = <error reading variable: Cannot access memory at address 0xaaaaaaaaaaaaaaaa>}, ref_count = 2863311530, qdata = 0xaaaaaaaaaaaaaaaa}, priv = 0xaaaaaaaaaaaaaaaa}
```

**Comment by awilfox** [comment]
Okay, thanks to some helpful people in the postmarketOS community, I was able to further track this down:

* Media needs to be playing using an MPRIS player (Audacious, VLC).  This makes Plasma 5 inhibit signals.
* Then, the screen needs to be locked.  This appears to cause the named pipe close.

Will continue debugging and see if I can find anything else.

**Comment by ajacoutot** [comment]
Hi @awilfox . Any chance on your debugging?
I am seeing the same on OpenBSD (which obviously does not use glibc either).

**Comment by awilfox** [comment]
Haven't found anything else out yet, but I am hoping to do so in the next week.

**Comment by ajacoutot** [comment]
Hi @awilfox 
Does this help?

```
Index: src/ck-inhibit.c
--- src/ck-inhibit.c.orig
+++ src/ck-inhibit.c
@@ -693,6 +693,11 @@ ck_inhibit_get_what (CkInhibit   *inhibit)
         string = check_event_and_add_to_string (inhibit, CK_INHIBIT_EVENT_HIBERNATE_KEY, "handle-hibernate-key", string);
         string = check_event_and_add_to_string (inhibit, CK_INHIBIT_EVENT_LID_SWITCH, "handle-lid-switch", string);
 
+        if (string == NULL) {
+                g_warning ("empty lock type received");
+                string = g_strdup("");
+        }
+
         return string;
 }
```

These seems to be some corruption somewhere and the lock type gets emptied which crashes ConsoleKit.
This is just a workaround.

**Comment by ajacoutot** [comment]
This should be fixed with https://github.com/ConsoleKit2/ConsoleKit2/commit/5d9925bae370cc1edc260909a55b44f6550294f1
Feel free to re-open in case it doesn't.
